"""Initial migration

Revision ID: c851c4d68c4e
Revises: 
Create Date: 2025-06-30 12:41:03.398816

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c851c4d68c4e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('restaurant',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(), nullable=False),
                    sa.Column('description', sa.String(), nullable=True),
                    sa.Column('image', sa.String(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.Column('category_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(
                        ['category_id'], ['category.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('favorite',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.String(), nullable=False),
                    sa.Column('restaurant_id', sa.Integer(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['restaurant_id'], ['restaurant.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('follow',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.String(), nullable=False),
                    sa.Column('restaurant_id', sa.Integer(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['restaurant_id'], ['restaurant.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('offer',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('title', sa.String(), nullable=False),
                    sa.Column('description', sa.String(), nullable=True),
                    sa.Column('original_price', sa.Float(), nullable=False),
                    sa.Column('offer_price', sa.Float(), nullable=False),
                    sa.Column('quantity', sa.Integer(), nullable=False),
                    sa.Column('start_datetime', sa.DateTime(), nullable=False),
                    sa.Column('end_datetime', sa.DateTime(), nullable=False),
                    sa.Column('restaurant_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['restaurant_id'], ['restaurant.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('order',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('offer_id', sa.Integer(), nullable=False),
                    sa.Column('buyer_id', sa.String(), nullable=False),
                    sa.Column('phone', sa.String(), nullable=False),
                    sa.Column('address', sa.String(), nullable=False),
                    sa.Column('quantity', sa.Integer(), nullable=False),
                    sa.Column('status', sa.Enum('PENDING', 'DELIVERED',
                                                'CANCELLED', name='orderstatus'), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.ForeignKeyConstraint(['offer_id'], ['offer.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order')
    op.drop_table('offer')
    op.drop_table('follow')
    op.drop_table('favorite')
    op.drop_table('restaurant')
    op.drop_table('category')
    # ### end Alembic commands ###
